export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;


export const UPDATE_LIST_NAME = 'UPDATE_LIST_NAME';
export type UPDATE_LIST_NAME  = typeof UPDATE_LIST_NAME;

export const CREATE_LIST = 'CREATE_LIST';
export type CREATE_LIST  = typeof CREATE_LIST;
